# http://www.appveyor.com/docs/appveyor-yml
# This is the standard AppVeyor project for the SDK
# It builds pulls requests and merges to master to ensure that no tests have broken
#
# This follows the 3-project AppVeyor/Maven pattern established in https://github.com/dblock/log4jna/blob/master/AppVeyorMavenRelease.md

# https://www.appveyor.com/docs/build-environment/#java
image: Visual Studio 2019

# Use the MSYS version of gpg, instead of the version bundled with git
init:
  - set PATH=C:\msys64\usr\bin;%PATH%

skip_tags: true

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  M2: $(USERPROFILE)\.m2
  SAMPLES_CLIENT:
    secure: gxzfCov2x367sdV+JO67q+6yHf0bjw0Rw99Fky+KdM0=
  SAMPLES_TOKEN:
    secure: L6PifAZNofYz4sqywztE/+s+pSTqmnUxqKbWYuIg+2MS7krLbynyZQhx+1lBKeSI

install:
  # Log versions for debugging
  - java -version
  - mvn --version
  - gpg --version

build_script:
  - mvn -B clean install -P ignore-tests-with-credentials

# Maven runs the tests as part of the build, so we don't need to run them again
test: off

cache:
  # Cache Maven and m.2
  - '%MAVEN_HOME%'
  - '%M2%'
