# http://www.appveyor.com/docs/appveyor-yml
# This is the standard AppVeyor project for the SDK
# It builds pulls requests and merges to master to ensure that no tests have broken
#
# This follows the 3-project AppVeyor/Maven pattern established in https://github.com/dblock/log4jna/blob/master/AppVeyorMavenRelease.md

# https://www.appveyor.com/docs/build-environment/#java
image: Visual Studio 2019

# Use the MSYS version of gpg, instead of the version bundled with git
init:
  - set PATH=C:\msys64\usr\bin;%PATH%

skip_tags: true

environment:
  JAVA_HOME: C:\Program Files\Java\jdk17
  M2: $(USERPROFILE)\.m2
  SAMPLES_CLIENT:
    secure: v7JAY2jKRI/baV1QkgJcyl8y13vm3e9l0/wtyGjE0p0=
  SAMPLES_TOKEN:
    secure: SSSmzL0pYmvelJF1FI1XM2tamFPemoH5i943o0lPUkd/TAxZCyaQYvgfS8FKZAj+

install:
  # Log versions for debugging
  - java -version
  - mvn --version
  - gpg --version

build_script:
  - mvn -B clean install

# Maven runs the tests as part of the build, so we don't need to run them again
test: off

cache:
  # Cache Maven and m.2
  - '%MAVEN_HOME%'
  - '%M2%'
